# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7eed0ecc4716f68165e28b461d6f1d7b3df197292b192367729d8525eba46dd4e80974638c886688e9f9a1b992ca2f4f4f9f89cfe46957c0b2801cd23287edc

test:
  secret_key_base: 1d5ab18cc02944da794f305cb778a5fecbfcd5aaba4ae9917411962b9ad48e30f7c93a34025d982118010eab730c7727b26e639308f5df428a5a56210d058277

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
